### ISSUE TITLE
SignalRTrigger Timeline

### ISSUE THREAD

**Issue by chaseWillden** [Azure/azure-functions-signalrservice-extension#111]
I do see that the SignalRTrigger is actively being worked on, any timeline when that will be released?

**Comment by JialinXin** [comment]
Yes, it's under tests and needs some ASRS management side support. And probably to release around May.

**Comment by michielpost** [comment]
I noticed that version 1.2.0 is released and this includes the `SignalRTrigger`. I tried to test the bidirectional-chat sample locally, but the SignalR triggers dit not work. Should it work locally? or does it only work when deployed to Azure Functions with the signalr_extensions App key enabled?

**Comment by zackliu** [comment]
@michielpost Some customers have tried bidirectional-chat sample and worked well. The sample can run locally and you need to have a public IP that you need to set in the upstream settings in SignalR Service. And if you're running locally, there's no `signalr_extensions` key and therefore `?code=xxx` it not needed in upstream settings.
What the problem are you meeting?
Besides, we just release some documents about the trigger. https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service-trigger?tabs=csharp
