### ISSUE TITLE
Serverless service and ASP Core

### ISSUE THREAD

**Issue by arek-avanade** [Azure/azure-functions-signalrservice-extension#125]
We'd like to make callbacks to SignalR clients in the following scenarios:
- From a time-triggered Function
- From ASP Core application (separate from my Functions of course)

From what I can see if I use Serverless SignalR Service, I could achieve the 1st goal by using SignalR output binding. However, I have no idea if the 2nd scenario is supported at all, but I could imagine there should be a way to make a callback to clients as far as I have connection string to my serverless SignalR service.

I saw in docs the 'Classic' mode could work for this scenario, but it is discouraged for some reason.

**Comment by arek-avanade** [comment]
Any feedback on that? Everyone on vacation? :)

**Comment by chenkennt** [comment]
Two options:
1. You can use [management SDK](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md) which provides similar functionality as function binding but can be used in any C# code.
2. You can still make your ASP.NET Core application a SignalR server (by using `AddAzureSignalR()`). In this approach the service mode needs to be "default" to allow server connections (classic also works but you already know it's not encouraged).

**Comment by arek-avanade** [comment]
@chenkennt Can you elaborate more on the 2nd option? Does it mean that I can still send messages with output binding from Azure Function even though the SignalR service is in 'default' mode? Of course my Azure Function would not have 'negotiate' endpoint in that case since ASP.NET Core app would negotiate client connections.

**Comment by chenkennt** [comment]
Yes, the main differences between serverless and default mode is whether it accepts server connections. With server connections messages from client are sent to server through server connections but in serverless mode they will be sent to an upstream server (if there is any) through web hooks. In your scenario you only want to send message from function to clients so default mode also works.

**Comment by arek-avanade** [comment]
Thanks @chenkennt ! I'm closing this issue in that case.
