### ISSUE TITLE
SignalRTrigger OnConnected with Traditional model

### ISSUE THREAD

**Issue by gerb0n** [Azure/azure-functions-signalrservice-extension#135]
I have a hard time getting a trigger on the 'OnConnected' event. Samples are only given with Class based model. 
And the **[docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service-trigger?tabs=csharp)** aren't really helpful for me.

I have the following:  
````
    public class SignalRHubFunction
    {
        [FunctionName("SignalRConnected")]
        public async Task Run([SignalRTrigger("myhubname", "connections", "connected", ConnectionStringSetting = "AzureSignalRConnectionString")] InvocationContext invocationContext, ILogger logger)
        {
            logger.LogInformation($"{invocationContext.ConnectionId} connected");
        }
    }
````

Docs are telling me the **category** parameter of the `SignalRTrigger` constructor should be:  **connections** or **messages**.
So I use **connections**.

> This value must be set as the category of messages for the function to be triggered. The category can be one of the following values:
connections: Including connected and disconnected events
messages: Including all other events except those in connections category

I don't really understand what the docs mean with the **event** parameter

> This value must be set as the event of messages for the function to be triggered. For messages category, event is the target in invocation message that clients send. For connections category, only connected and disconnected is used.

I guess they are saying you can choose between **connected** and **disconnected**.

However with the code from above the trigger is never hit. Any thoughts?

**Comment by gerb0n** [comment]
For anyone wondering the same: I ended up using an EventGrid-trigger as suggested by the Azure team themselves: youtube.com/watch?v=VTVqV0hZ1EQ. From there I used an `IAsyncCollector<SignalRGroupAction>` to add the user to a specific group.

**Comment by zackliu** [comment]
I tried the code you provided but can't reproduce your problem. The `SignalRConnected` was successfully triggered. Did you tried class based model? Can it be successfully triggered? I think you codes is totally correct.

**Comment by gerb0n** [comment]
Okay, well thanks for confirming the code is right. The class based model also didn't work so there must be a configuration issue.
