### ISSUE TITLE
SignalRConnectionInfoAttribute headers binding is case-sensitive

### ISSUE THREAD

**Issue by look-im-not-your-daddy** [Azure/azure-functions-signalrservice-extension#136]
https://github.com/Azure/azure-functions-signalrservice-extension/blob/6007d486222672eb027c5176b72c10436b084e91/src/SignalRServiceExtension/SignalRConnectionInfoAttribute.cs#L22

I noticed it uses `[AutoResolve]` but didn't find what's being used in runtime to resolve that value, therefore I'm opening here.

The problem is that HTTP Headers are supposed to be case-insensitive as per [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2). 

Please let me know if the specified RFC is not the correct assumption or if I should open this issue for the specific value resolver used in the `{headers.` case. For the latter, please point me to this resolver.

Thank you.

**Comment by look-im-not-your-daddy** [comment]
Related to https://github.com/MicrosoftDocs/azure-docs/issues/63382.

**Comment by wanlwanl** [comment]
have you tried to change the upper/lower case of:

* function side: https://github.com/Azure/azure-functions-signalrservice-extension/blob/master/samples/simple-chat/content/index.html#L171
* client side: https://github.com/Azure/azure-functions-signalrservice-extension/blob/master/samples/simple-chat/csharp/FunctionApp/Functions.cs#L28

They are already insensitive

**Comment by look-im-not-your-daddy** [comment]
Hello @wanlwanl, sorry not posting src before. I think now it's gonna be a bit more clearer to understand the problem.

Consider the following:

```csharp
    public static class Negotiate
    {
        [FunctionName("negotiate")]
        public static IActionResult Run
        (
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "notifications/negotiate")] HttpRequest request,
            [SignalRConnectionInfo(HubName = HubName, UserId = "{headers.x-my-custom-header}")] SignalRConnectionInfo connectionInfo
        ) => new OkObjectResult(connectionInfo);
    }
```

No consider the following requests:

`GET /notifications/negotiate`
- containing the header: **`x-my-custom-header`**
Response Status Code: **`200`**

`GET /notifications/negotiate`
- containing the header: **`X-MY-CUSTOM-HEADER`**
Response Status Code: **`500`** (on App Insights I see an exception saying that the header `x-my-custom-header` was not found)

That's the problem.

**Comment by wanlwanl** [comment]
Could you share a minimal reproducible project?
I tried with the latest function binding code, it seems work.

You can try this PR (simply change the header to upper case): https://github.com/Azure/azure-functions-signalrservice-extension/pull/144
The step to try is in the description in the PR.

**Comment by look-im-not-your-daddy** [comment]
That's my project:

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <AzureFunctionsVersion>v3</AzureFunctionsVersion>
        <AssemblyName>asdf</AssemblyName>
        <UserSecretsId>00000000-0000-0000-0000-000000000000</UserSecretsId>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.19" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.1.2" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.SignalRService" Version="1.2.1" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.2" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />
    </ItemGroup>
    <ItemGroup>
        <None Update="host.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="local.settings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
    </ItemGroup>
</Project>

```

I'm not on the JS side yet and I don't think it's necessary since the GET /notifications/negotiate request it's just a simple HTTP request with some headers, thing that can be done via Postman or curl.

**Comment by wanlwanl** [comment]
Yes, not necessary, js client is only used for send request in this case, also tried with postman.

**Comment by look-im-not-your-daddy** [comment]
What about my packages' versions? Matching yours? I'll look my Azure environment to see what's different.

**Comment by wanlwanl** [comment]
This is mine:
https://github.com/Azure/azure-functions-signalrservice-extension/blob/wanl/header/samples/simple-chat/csharp/FunctionApp/FunctionApp.csproj

**Comment by look-im-not-your-daddy** [comment]
BTW, not sure it's clear by now but that's happening when I'm running on the Azure infrastructure (https://asdf.azurewebsites.net/api/notifications/negotiate) and not locally.

**Comment by wanlwanl** [comment]
Tried 1.2.1 for signalr binding extension, works well.
I think you can run your function app locally to see if it's able to reproduce locally. If not, please create a ticket to azure function team.

**Comment by look-im-not-your-daddy** [comment]
I'm afraid you're running a very different thing.

Yours: `<TargetFramework>netstandard2.0</TargetFramework>`
Mine: `<TargetFramework>netcoreapp3.1</TargetFramework>` 

Yours: `<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.29" />`
Mine: `<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />`

Yours: `<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />`
Mine: `<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.SignalRService" Version="1.2.1" />`

So I believe it's unfair to say that you're replicating and it's not happening to you. Of course, you're using much older libraries and very different setup. My src uses latest.

**Comment by wanlwanl** [comment]
I only check for the signalr binding extension. It turned out that the signalr binding extension works. 
If you believe it's caused by something out of signalr binding extension, then here's the not the right place to create the issue. 
I suggest you create a ticket for your function app in azure portal, it should be the best way to get the right team to handle the issue, the support person will track the case all the rime and transfer the case to the right team if necessary.

**Comment by look-im-not-your-daddy** [comment]
I just would like you to replicate precisely my project to make sure it's not in your side (or if you know/could point who does that `{headers.` binding) or we will both look like amateurs later when I open this issue on the functions repo and they point back to your repo.

If you're already using 1.2.1 for the Extensions.SignalRService, so the last thing to check is to set netcoreapp3.1 and try to replicate again.

My functions is running on Windows with runtime version 3.0.14492.0.

Then yes, I'll follow your suggestion and open an issue at the functions repo.

**Comment by wanlwanl** [comment]
Still works well. updated the PR. I'm wondering if you include the header? I suggest you check what's in the headers first.

**Comment by look-im-not-your-daddy** [comment]
Thanks for the tip. Some things are so basic that that we get blind to it.

It happens that I was testing this in a proxy-protected environment and my headers were being messed up. Tested with no proxy now and I'm not able to reproduce anymore so shame on me.

Appreciate your patience and apologies for the time spent on it.
