### ISSUE TITLE
Multiple endpoint support for Azure SignalR Server-less scenarios

### ISSUE THREAD

**Issue by Y-Sindo** [Azure/azure-functions-signalrservice-extension#145]
### Description
Today configuring multiple endpoints is not yet supported when Azure SignalR is used under server-less scenarios, including using the Management SDK, or using Function bindings.

The feature would include the following for both Management SDK and Function extension:
1. Allow user to configure multiple endpoints
1. Allow user to configure the routing strategy
1. Able to detect failed endpoints and do fail-over

### Done

* [Management SDK ](https://github.com/Azure/azure-signalr) support
- [x] https://github.com/Azure/azure-signalr/pull/1105
- [x] https://github.com/Azure/azure-signalr/pull/1070
- [x] Supports multiple endpoints in negotiation.
- [x] Set up multiple endpoints in function binding
- [x] Customize router in C#
- [x] [Release 1.3.0 ](https://github.com/Azure/azure-functions-signalrservice-extension/releases/tag/v1.3.0)
- [x]  customize router for other language
- [x] Release customize router for other language feature
- [x] [Release 1.4.0](https://github.com/Azure/azure-functions-signalrservice-extension/releases/tag/v1.4.0)

### Waiting
- [ ] SignalR extension version update in extension bundles: https://github.com/Azure/azure-functions-extension-bundles/pull/78

**Comment by wanlwanl** [comment]
any related issues?

**Comment by Y-Sindo** [comment]
> any related issues?

[Release 1.3.0](https://github.com/Azure/azure-functions-signalrservice-extension/releases/tag/v1.3.0) is included in the **Done** section.

**Comment by Y-Sindo** [comment]
It's already supported in the latest versions.
