### ISSUE TITLE
Expression Bindings for SignalRTrigger HubName do not function.

### ISSUE THREAD

**Issue by holtalanm** [Azure/azure-functions-signalrservice-extension#159]
Issue:

Using Expression Bindings (https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns#binding-expressions---app-settings) for the SignalRTrigger HubName property (I didn't check other properties, but I assume they may have similar issues) does not cause it to resolve the HubName from application settings.

i.e. setting HubName to something like `%SignalRHubName%` doesn't actually bind based on application settings.

Reproduction:

I set up a github project illustrating what I am seeing.  The project contains three Functions -- one for Negotiate, and two OnConnected functions.  One of the OnConnected functions resolves the HubName using a binding expression, while the other does not.   When running both projects within the solution, the "SignalRTester" will connect to the function app as a SignalR Hub.

I tried to make this reproduction as simple as possible.

https://github.com/holtalanm/SignalRBindingExpressions.Example

Expected:

Function app should fail on startup, claiming two OnConnected bindings for the same HubName.

-or-

Both OnConnected functions should execute when a SignalR client connects. ??

(You could remove the `OnConnected_NoExpressionBinding` function if you want -- the `OnConnected_ExpressionBinding` function never executes, regardless)

Actual:

Only the `OnConnected_NoExpressionBinding` function executes when a SignalR client connects.

**Comment by holtalanm** [comment]
Looks like it was never implemented?

https://github.com/Azure/azure-functions-signalrservice-extension/blob/ef7bd21feecf5278c0bcaf487c929a1e5446448e/src/SignalRServiceExtension/TriggerBindings/SignalRTriggerBindingProvider.cs#L60

**Comment by Y-Sindo** [comment]
As the fix is released with 1.3.0, close the issue.
