### ISSUE TITLE
Allow ability to grab the hub name from configuration

### ISSUE THREAD

**Issue by ianmccaul** [Azure/azure-functions-signalrservice-extension#177]
Would love to ability to be able to configure the hub name based on environment variables. This would allow us to use a single signalr service as a host for multiple hubs in an environment. Right now its just a constant string passed in.

**Comment by anthonychu** [comment]
You should be able to use the `%VARIABLE_NAME%` syntax to do this. https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns#binding-expressions---app-settings

**Comment by Y-Sindo** [comment]
Since 1.3.0, we should be able to `AutoResolve` hub name in SignalR trigger binding. Other binding should always work.
