### ISSUE TITLE
Bidirectional Example is not sending messages

### ISSUE THREAD

**Issue by granadytos** [Azure/azure-functions-signalrservice-extension#236]
When i tried to send a message (as admin or not admin user) i am having an Error: Invocation failed, status code 401
![image](https://user-images.githubusercontent.com/4931321/119393561-bbfd7b80-bc96-11eb-8c79-a715f36080a2.png)

Negotiation step is correctly solved 
![image](https://user-images.githubusercontent.com/4931321/119394716-219e3780-bc98-11eb-888d-f4146d04934c.png)

![image](https://user-images.githubusercontent.com/4931321/119394413-c1a79100-bc97-11eb-93f3-dd0bac704212.png)

**SignalR Service Settings:**

-Upstream settings done:
![image](https://user-images.githubusercontent.com/4931321/119393814-0f6fc980-bc97-11eb-8505-7bc9e0e88d23.png)
- CORS allowed All:
![image](https://user-images.githubusercontent.com/4931321/119393882-26162080-bc97-11eb-8eee-b57de62f7b6f.png)

**Function App Settings**
- signalr_extensions done:
![image](https://user-images.githubusercontent.com/4931321/119393988-4ba32a00-bc97-11eb-9623-80c45bb125da.png)
- azuresignalr connectionstring done:
![image](https://user-images.githubusercontent.com/4931321/119394133-755c5100-bc97-11eb-9781-b5cbac79ddd8.png)
- CORS 

![image](https://user-images.githubusercontent.com/4931321/119394946-72ae2b80-bc98-11eb-88e2-cdeacc71571f.png)

**Comment by Y-Sindo** [comment]
Your upstream URL is wrong. It should be like `<Function_App_URL>/runtime/webhooks/signalr?code=<API_KEY>` .

**Comment by granadytos** [comment]
Thank you i changed the misconfigured settings and it worked. !
