### ISSUE TITLE
Multiple Azure SignalR Service Instances Support for .NET 5

### ISSUE THREAD

**Issue by JialinXin** [Azure/azure-functions-signalrservice-extension#262]
Copied from https://github.com/Azure/azure-functions-dotnet-worker/issues/566

> I would like to use multiples AzureSignalRConnectionString to connect with Azure SignalR Service. But I can't do it on Azure 
 Function with .NET 5.
> I was trying to follow this documentation Multiple Azure SignalR Service Instances Support in Azure Functions, but it looks like that works only in a .NET Core App 3.1 version that uses Microsoft.Azure.WebJobs.Extensions.SignalRService package.

@jairzjunior

**Comment by JialinXin** [comment]
@Y-Sindo Can you help take a look?

**Comment by Y-Sindo** [comment]
Already added a comment in the original issue.

**Comment by Y-Sindo** [comment]
Supported.
