### ISSUE TITLE
Add support to `DefaultAzureCredential` authentication via `Azure.Identity` library

### ISSUE THREAD

**Issue by ilya-git** [Azure/azure-functions-signalrservice-extension#269]
Right now the connection string supports Managed Identity like this:

`Endpoint={signalr_service_endpoint};AuthType=aad;Version=1.0;`

This is very nice and useful, but the problem is that for local development I would still have to revert to `AccessKey` and cannot use e.g. `Azure CLI` or `Environment variables` authentication that `Azure.Identity` provides via `DefaultAzureCredential`.

It would be very nice if we can have `AuthType` like `aaddefault` or some similar way of using it so that we won't need to supply secrets like access key for running locally.

**Comment by Y-Sindo** [comment]
It is supported in #265 , and will be released in next month.

**Comment by ilya-git** [comment]
How could it be turned on? Or the existing connection string would just "work"?

By the way if I use this connection string locally there are no errors, everything seems to work, but messages don't come trhough.

**Comment by Y-Sindo** [comment]
>How could it be turned on? Or the existing connection string would just "work"?

It is different with connection string. From the view of JSON, it uses a JSON object instead of one JSON key-value pair to configure a SignalR Service connection. For example, you can use the following configuration to get a `DefaultAzureCredential`.
```json
{
    "AzureSignalRConnectionString": {
        "serviceUri": "https://{SignalRHost}"
    }
}
```
Detailed documents will be provided once released.

> By the way if I use this connection string locally there are no errors, everything seems to work, but messages don't come trhough.

This is another issue. You could open another issue and give more details about your problem.

**Comment by ilya-git** [comment]
Thanks for help, I will wait for the release and documentation! I know it is another issue, but since it was never officially supported to do what I tried, it's not very important for me that it gets fixed, just weird that there were no errors :)

**Comment by Y-Sindo** [comment]
> Thanks for help, I will wait for the release and documentation! I know it is another issue, but since it was never officially supported to do what I tried, it's not very important for me that it gets fixed, just weird that there were no errors :)

Thank you for your feedback. The log problem of function environment is indeed mentioned by some users. We will consider provide a trouble shooting guide for this in the future.

**Comment by Y-Sindo** [comment]
@ilya-git A quick update about the logging problem, you can see [Configure Log Level](https://docs.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2#configure-log-levels) to ger more logs.

**Comment by Y-Sindo** [comment]
It is supported in v1.6.0
