### ISSUE TITLE
Nuget install of 1.6.0 fails due to unreleased dependency

### ISSUE THREAD

**Issue by kianryan** [Azure/azure-functions-signalrservice-extension#276]
```
dotnet add package Microsoft.Azure.WebJobs.Extensions.SignalRService --version 1.6.0
```

error: NU1102: Unable to find package Microsoft.Azure.SignalR.Serverless.Protocols with version (>= 1.6.0)
error:   - Found 8 version(s) in nuget.org [ Nearest version: 1.5.0 ]
error:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages

1.5.0 is highest available version of Microsoft.Azure.SignalR.Serverless.Protocols.

**Comment by cbbrsc** [comment]
I have the same problem. It looks like the Microsoft.Azure.SignalR.Serverless.Protocols 1.6.0 is missing from nuget. 

SU1102	Unable to find package Microsoft.Azure.SignalR.Serverless.Protocols with version (>= 1.6.0)
  - Found 8 version(s) in nuget.org [ Nearest version: 1.5.0 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages

**Comment by Y-Sindo** [comment]
Sorry it is a mistake. Now the problem is fixed.
