### ISSUE TITLE
Serialisation with Multiple Instances of Azure signal R

### ISSUE THREAD

**Issue by Dewaldf** [Azure/azure-functions-signalrservice-extension#277]
I am trying to connect my function to multiple instances of azure signal r , as explained in [this document ](https://github.com/Azure/azure-functions-signalrservice-extension/blob/dev/docs/sharding.md#configuration-method)

The problem I have is that the property names on my payload has changed to camelCase. I am guessing this is because System.Text.Json is now used for serialization. I tried to use NewtonSoft by adding `Azure__SignalR__HubProtocol=NewtonsoftJson` to my settings, but the case remains the same.

How can change this to be using Pascal case again, while still being able to connect to multiple instances of Azure signal r ?

**Comment by Y-Sindo** [comment]
~~Only adding `Azure__SignalR__HubProtocol=NewtonsoftJson` uses the `new JsonSerializerSettings()` setting. You could also add 
`Azure__SignalR__HubProtocol__NewtonsoftJson__CamelCase=true` to enable camel case.~~

**Comment by Dewaldf** [comment]
I tried this `Azure__SignalR__HubProtocol__NewtonsoftJson__CamelCase=false` , cause I do not want camel case, but still having the issue, according [to this](https://github.com/Azure/azure-functions-signalrservice-extension/issues/271#issuecomment-916634952) it is known that it will not work

**Comment by Dewaldf** [comment]
I Installed the latest Microsoft.Azure.WebJobs.Extensions.SignalRService package , working now.
