### ISSUE TITLE
MessagePack for Output bindings

### ISSUE THREAD

**Issue by runtimeware** [Azure/azure-functions-signalrservice-extension#281]
Having trouble finding the answer reading through the docs and the code - but is there a way to configure the extension to use MessagePack for signalr messages brokered over the output bindings (or anything else for that matter)?

**Comment by Y-Sindo** [comment]
With `transient` transport type (the default one), your JSON payload is converted into MessagePack payload automatically in the Azure SignalR Serive side. So you could have MessagePack client together with JSON client under `transient` transport type. However, you can't customize the MessagePack serialization.
