### ISSUE TITLE
Add support for groups

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-signalrservice-extension#29]
## Broadcast to a specific group

* Add `groupName` property
* If `groupName` is populated, only send the message to the group
* If both `groupName` and `userId` are specified, throw exception

```javascript
{
    "groupName": "groupName1",
    "target": "targetMethodName",
    "arguments": [ "arg1", "arg2" ]
}
```

## Add user to group, remove user from group

* Add a `SignalRGroupAction` output binding

```javascript
{
  "action": "add", // or "remove"
  "userId": "user id",
  "groupName": "groupName1"
}
```

Needs bindings to be updated to use the V1 API #28 

@chenkennt Thoughts?

**Comment by ChristianWeyer** [comment]
Please make it easy to add users to groups.
E.g. today in SignalR we can do this:

namespace Hubs
{
    [Authorize]
    public class OrdersHub : Hub
    {
        public override Task OnConnectedAsync()
        {
            var identity = Context.User.Identity as ClaimsIdentity;
            var subjectId = identity?.Claims.FirstOrDefault(c => c.Type == "sub")?.Value;

            Groups.AddToGroupAsync(Context.ConnectionId, subjectId);

            return base.OnConnectedAsync();
        }
    }
}

**Comment by anthonychu** [comment]
@ChristianWeyer This is roughly how the current proposal would look like in C# with App Service Authentication.

```csharp
[FunctionName("AddToGroup1")]
public static void AddToGroup1(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post")]HttpRequest req, 
    [SignalRGroupAction(HubName = "chat")] out SignalRGroupAction groupAction)
{
    req.Headers.TryGetValue("x-ms-client-principal-name", out var caller);
    groupAction = new SignalRGroupAction
    {
        Action = GroupAction.Add,
        UserId = caller,
        GroupName = "Group1"
    };
}
```

**Comment by davidfowl** [comment]
Part of me wonders if we should just expose a similar API to the [IHubClients](https://github.com/aspnet/SignalR/blob/596f8acce1f16f30c83ba99f0b7d337778e2fdc8/src/Microsoft.AspNetCore.SignalR.Core/IHubClients%60T.cs#L12) and [IGroupManager](https://github.com/aspnet/SignalR/blob/596f8acce1f16f30c83ba99f0b7d337778e2fdc8/src/Microsoft.AspNetCore.SignalR.Core/IGroupManager.cs#L12)

**Comment by anthonychu** [comment]
We should consider this for .NET functions and look into supporting binding to those 2 interfaces (or similar interfaces) in addition to IAsyncCollector.

**Comment by davidfowl** [comment]
Sounds good to me. BTW we don't have to take a hard dependency on the type but making them look more like method calls might be more natural (but I may be biased 😄 )

**Comment by anthonychu** [comment]
Not biased at all. 😄 It makes perfect sense to do this for .NET functions. So far we've focused on supporting IAsyncCollector as it's the common denominator for all languages.

**Comment by grahamehorner** [comment]
@davidfowl @anthonychu sounds very interesting, but I'm wondering if the IAsyncCollector is the correct binding to use, if a developer needs to query the collection of groups/uses and not just simply doing an AddAsync ? loving AzureFunctions & SignalR as a Service BTW +1000 from me

**Comment by anthonychu** [comment]
@grahamehorner Currently there isn't a way to query groups and users from the service. If that ever gets added, we might supply an input binding to query this info for all languages. It would make sense to add richer support to .NET functions by binding to an interface that can add/remove/query users.

**Comment by grahamehorner** [comment]
@anthonychu @davidfowl how would you vision an AzureFunctions application using SignalR as a Service having the ability to 'kick a user' from a given group(s) ?

**Comment by JialinXin** [comment]
Release with version: 1.0.0-preview1-10025
