### ISSUE TITLE
Azure Service shows zero message count, but Function shows no errors?

### ISSUE THREAD

**Issue by ryancole** [Azure/azure-functions-signalrservice-extension#41]
I'm trying out the Azure Functions SignalR binding.

I've got an Azure SignalR service up and running in Azure. I've got the connection string for that SignalR Service configured in my Functions app. I've got a single Function triggered by Service Bus with a return SignalR binding.

I can execute the Function locally / manually via the admin URL and I can execute the function via Service Bus - both situations the function completes without error, but my SignalR Service never appears to receive any message? (Unless that message-count-over-time graph does not work)

I've also got a JavaScript client connected to the SignalR Hub via WebSocket and it never receives anything from the SignalR Service.

Here's the code for my Function. The `payload.Message` is just a simple string, like "Hello!". Do you see anything wrong, or is there a way I can enable more verbose logging? Thanks!

```cs
namespace FoundryFunctions.SignalrBroadcast
{
    public static class Function
    {
        [FunctionName("Broadcast")]
        public static async Task Run(
            [ServiceBusTrigger("handler-signalr-broadcast", Connection = "AzureWebJobsServiceBus")] string message,
            [SignalR(HubName = "functions")] IAsyncCollector<SignalRMessage> messages)
        {
            var entry = JsonConvert.DeserializeObject<FoundryPipelineEntry>(message);
            var payload = JsonConvert.DeserializeObject<SignalrBroadcastPayload>(entry.Payload);

            var result = new SignalRMessage
            {
                Target = "echo",
                Arguments = new [] { payload.Message }
            };

            await messages.AddAsync(result);
        }
    }
}
```

**Comment by ryancole** [comment]
I download Fiddler to log the HTTP requests and it does indeed look like the Function is sending the POST request straight to the Azure SignalR Service. The service is responding with the Accepted response. So that does look like it's working.

I guess my issue is elsewhere in the SignalR setup of mine. None of my connected clients are receiving this message.

**Comment by BouchardClaude** [comment]
Hi ryancole, I have the same issue using Azure SignalR and Azure funtion to send data and I cant figure out whats wrong... Have you by luck figured out what was wrong with your setup ?  thx ;-)

**Comment by tmutton** [comment]
I'm having the same issue. Does a client need to be connected for the messages to show up in the Azure SignalR Hub?

**Comment by martin-weber** [comment]
Same issue.

**Comment by orizzonte** [comment]
Anyone figured out a solution?  Same issue here.

**Comment by mzuhaq7** [comment]
Im also facing the same issue. Ive tried everything. Did anyone find the solution?

**Comment by Y-Sindo** [comment]
The unit of message counted is 2Kb, so if the size of messages you sent is lower than 2Kb, you would see a count of zero. See more details here: [How messages are counted for billing](https://learn.microsoft.com/azure/azure-signalr/signalr-concept-messages-and-connections#how-messages-are-counted-for-billing)

**Comment by mzuhaq7** [comment]
Thanks for replying, but Ive tried sending multiple messages of 3Kb but still message count on azure signalR is zero and there's no exception thrown either

```[FunctionName("SendMessage")]
public static async Task SendMessage(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post")] string message,
    [SignalR(HubName = "BroadcastHub", ConnectionStringSetting = "AzureSignalRConnectionString")] IAsyncCollector<SignalRMessage> signalRMessages)
{
    try
    {      
        await signalRMessages.AddAsync(
            new SignalRMessage
            {
                Target = "newMessage",
                Arguments = new[] { message }
            });
    }
    catch (Exception ex)
    {
        Console.Write(ex.Message);
    }
}

**Comment by Y-Sindo** [comment]
@mzuhaq7 
> [The message count chart in the Azure portal is updated every 100 messages per hub. ](https://learn.microsoft.com/azure/azure-signalr/signalr-concept-messages-and-connections#how-messages-are-counted-for-billing)

Do your SignalR clients receive the messages? If not, please send an email to zityang@microsoft.com  with your SignalR resource ID and a timestamp when you sent messages.

**Comment by mzuhaq7** [comment]
Thanks @Y-Sindo , i found the issue.. The issue was that message count on azure signalR is zero until a client receives the message. So when i was pushing message to azure signalR and no client was listening, it showed zero message count but as soon as i connected a client, messages were being received and message count was no longer zero. Here is the code for listening to messages in case someone else faces the same issue. 
```
string endpoint = "your-endpoint"; 
            HubConnection connection = new HubConnectionBuilder()
                .WithUrl(endpoint, options =>
                        {
                            options.AccessTokenProvider = () => Task.FromResult(signalRConnectionInfos.AccessToken);
                        })
                .Build();

                connection.On<string>("newMessage", (message) =>
                {
                    Console.WriteLine($"Received message: {message}");
                });

                await connection.StartAsync();
                Console.WriteLine("Connection started");
                while (true) {     
                }

**Comment by Y-Sindo** [comment]
@mzuhaq7 Yes, 
> Only outbound messages from Azure SignalR Service are counted for billing. Ping messages between clients and servers are ignored.
