### ISSUE TITLE
Can Azure Function be Called from SignalR Client or Hub?

### ISSUE THREAD

**Issue by yasin-uohyd** [Azure/azure-functions-signalrservice-extension#45]
Hi Team,

1. Is there any way, I can call Azure function from a SignalR Client or Hub?
2. Can register my Azure function as a SignalR client using Azure SignalR Service?

**Comment by anthonychu** [comment]
1. Not yet. We're looking into ways to enable clients to invoke server-side code using the SignalR connection.
1. Can you please explain this one a bit more? Do you want to use the SignalR client SDK to connect as a client to a SignalR Service instance?

**Comment by yasin-uohyd** [comment]
for 2:
Rephrasing my question: Can my Azure Function be act like a SignalR Service Client, which has only one method? As of now, we have feature to Broadcast from a Azure Function, I believe, we might be using REST capabilities of SignalR Service.

**Comment by anthonychu** [comment]
I think the answer is "no" and I don't know of any plans to support this. Can you provide more information on the scenario or why it is needed? Thanks.

**Comment by zackliu** [comment]
@yasin-uohyd We just release the `SignalRTrigger` that allows you to invoke Azure Function from a SignalR client.
The feature is provided since version 1.2.0 and here's the document. https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service-trigger?tabs=csharp

**Comment by yasin-uohyd** [comment]
Thanks @zackliu .
