### ISSUE TITLE
1.0.0 Release Nuget Package

### ISSUE THREAD

**Issue by gorillapower** [Azure/azure-functions-signalrservice-extension#51]
We are getting errors when trying call out to our Azure SignalR instance on the negotiate stage. It seems port 5001/5002 has been deprecated but the library still uses these ports. I see this has been fixed in V1.0.0, will there be a nuget package release soon to solve this?

**Comment by JialinXin** [comment]
Yes, we just publish to v1.0.0 that use 443 completely. Actually if you're working on preview-10025, you can automatically use v1 API(port 443) by updating your connection string with Version=1.0 assigned in the end. See [here](https://github.com/Azure/azure-signalr/issues/123#issuecomment-455035556) for reference.

**Comment by JialinXin** [comment]
@gorillapower Please check and let us know if it works.

**Comment by gorillapower** [comment]
@JialinXin, thank you! I added Version=1.0 in the connection string and is now connecting as expected.
