### ISSUE TITLE
How can we setup a secondary connection string?

### ISSUE THREAD

**Issue by redtaped** [Azure/azure-functions-signalrservice-extension#67]
We are trying to implement the recommendations found here: [Resiliency and disaster recovery](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-disaster-recovery), but are having trouble implementing a **secondary** connection string for Azure Functions using the SignalR service bindings.

SignalR service bindings should support a secondary connection string.

**Comment by pradeepjaladi** [comment]
Was this supported yet? When I am going the docs of Azure SignalR service I found an article [Scale Multiple instances] (https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-scale-multi-instances) and seems like there is no way for Azure functions to support it. Please let me know if you guys are planning to implement it.

**Comment by realwanpengli** [comment]
It is not supported, but it sounds useful. I will update if any plan for it.

**Comment by mbinggeli** [comment]
I would agree; this is very important to have redundancy.

**Comment by AndreasFurster** [comment]
Is this feature planned yet? What would it take to implement it?

**Comment by chenkennt** [comment]
It's planned already. For now a workaround can be found here: https://github.com/Azure/azure-signalr/issues/972

Will update this issue once the feature is released.

**Comment by gavinbarron** [comment]
It looks like #155 is intended to address this. 
@Y-Sindo is this PR the work that will unlock this? If so what's the timeline to that rolling out for use?

**Comment by Y-Sindo** [comment]
> It looks like #155 is intended to address this.
> @Y-Sindo is this PR the work that will unlock this? If so what's the timeline to that rolling out for use?

Currently we only support multiple-endpoints for persistent mode. If you use persistent mode and use C# as function language, then it's already OK. If you use other languages such JS, and you don't need to [customize route algorithm](https://github.com/Azure/azure-signalr/blob/dev/docs/sharding.md#customize-router), then also yes. 

If the current Azure Function SignalR extension already fulfills some users' need such as yours, we'd consider release it at this point.

**Comment by gavinbarron** [comment]
We are using C# as the function language and want to be able to use the convention based configuration to set up primary and secondary/backup SignalR service instances in Azure to provide a HA configuration for the negotiate function.

So, yes, I think that the current Azure Function SignalR extension will fulfill our needs. Is the configuration on the function app to add multiple app settings in the form:
```
Azure:SignalR:ConnectionString:east-region-a:primary 
Azure:SignalR:ConnectionString:east-region-b:primary
Azure:SignalR:ConnectionString:west-region-a:secondary
Azure:SignalR:ConnectionString:west-region-b:secondary
```
How then do you bind the ConnetionInfo Input to your function for negotiate? Like this?:
```
[SignalRConnectionInfo(HubName = "MessageHub", ConnectionStringSetting= "Azure:SignalR:ConnectionString")] SignalRConnectionInfo connectionInfo)
```

**Comment by Y-Sindo** [comment]
>   Is the configuration on the function app to add multiple app settings in the form:
>   ```
>   Azure:SignalR:ConnectionString:east-region-a:primary 
>   Azure:SignalR:ConnectionString:east-region-b:primary
>   Azure:SignalR:ConnectionString:west-region-a:secondary
>   Azure:SignalR:ConnectionString:west-region-b:secondary
>   ```
>   How then do you bind the ConnetionInfo Input to your function for negotiate? Like this?:
>   ```
>   [SignalRConnectionInfo(HubName = "MessageHub", ConnectionStringSetting= "Azure:SignalR:ConnectionString")] SignalRConnectionInfo connectionInfo)
>   ```

Your sample should be right.

**Comment by gavinbarron** [comment]
That's great thank you :)
I'm still a little unclear when we will be able to use this in our applications

**Comment by Y-Sindo** [comment]
We are going to release it in about three weeks.

**Comment by Y-Sindo** [comment]
Now you can try the multiple-endpoint support with 1.3.0 version on myget. https://www.myget.org/feed/azure-signalr-dev/package/nuget/Microsoft.Azure.WebJobs.Extensions.SignalRService/1.3.0 

The preview version of document: https://github.com/Azure/azure-functions-signalrservice-extension/pull/179

**Comment by planty** [comment]
This looks great, thanks. 
Is transient the default transport type? What would be the impact of switching to persistent for azure functions using signalr service? why isn't persistent the default?

**Comment by Y-Sindo** [comment]
> This looks great, thanks.
> Is transient the default transport type? What would be the impact of switching to persistent for azure functions using signalr service? why isn't persistent the default if it is presumably more efficient ?

Yes, transient type is the default. Because transient type was developed ahead of persistent type and was once the only type, to make it default keeps backward compatibility.

For the impact of switching to persistent : 
From .Net Core 3.0, SignalR starts to use  System.Text.Json as the JSON library for the default JSON protocol. If you use persistent type on Azure Functions V3 runtime, the default hub protocol will be the JSON protocol based on  System.Text.Json. You can also configure to switch back to Newtonsoft.Json by adding an configuration entry: 

* On `local.settings.json` :
  ```json
  {
  "Azure:SignalR:HubProtocol":"NewtonsoftJson"
  }
  ```
* On Application Settings on Azure Portal,  change `:` to `__` as it is actually environment variable configuration :
   `Azure__SignalR__HubProtocol = NewtonsoftJson`

See also: [How to migrate from Newtonsoft.Json to System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-core-3-1)

**Comment by Y-Sindo** [comment]
An update: `Microsoft.Azure.WebJobs.Extensions.SignalRService` 1.3.0 can be retrieved on Nuget now.
