### ISSUE TITLE
Is camel case supported?

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/azure-functions-signalrservice-extension#74]
I've [posted a question here](https://stackoverflow.com/questions/58012236/making-azure-function-signalr-payloads-camel-case) regarding how to have azure signalR functions support camel case payloads. Would you please advise on the question?

**Comment by Arash-Sabet** [comment]
Got the answer. The conversion to camel case should happen in the tier where the message object is prepared.

**Comment by vova-lantsov-dev** [comment]
For those who are looking for this nowadays, the actual way is described here: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/samples/Sample02_CustomizingJsonSerialization.md

```csharp
builder.Services.Configure<SignalROptions>(o => o.JsonObjectSerializer = new NewtonsoftJsonObjectSerializer(
    new JsonSerializerSettings
    {
        ContractResolver = new CamelCasePropertyNamesContractResolver(),
        Converters =
        {
            new StringEnumConverter(typeof(DefaultNamingStrategy))
        }
    }));
```

**Comment by Arash-Sabet** [comment]
Thanks @vova-lantsov-dev
