### ISSUE TITLE
Add support to remove a user from All Groups

### ISSUE THREAD

**Issue by brunhil** [Azure/azure-functions-signalrservice-extension#75]
It would be great to be able to remove a user from all groups.

The REST API supports this: https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md#remove-a-user-from-all-groups

Something could be added for the current SignalRGroupActions, such as SignalRGroupAction.RemoveFromAll.

**Comment by realwanpengli** [comment]
Yeah, that's great.
