### ISSUE TITLE
ConnectionInfo

### ISSUE THREAD

**Issue by Raedg13** [Azure/azure-functions-signalrservice-extension#82]
Is it possible to set the name of the hub and the Azure SignalR connection inside the code of an Azure Function? That is not to use binding!!

The class AzureSignalRClient is internal? Why don't you make it public?

regards,
Raed

**Comment by JialinXin** [comment]
Why do you need to hard code connection string? It's not a correct behavior with potential security issue.

**Comment by Raedg13** [comment]
I do not want to hard code the connection information inside the code. But I want to be able to from inside my function to query the hub name and connection information from a service depending on the user.

**Comment by JialinXin** [comment]
The function is always target a hub, so you'd know which hub is in use directly. So what else connection information do you need?

**Comment by Raedg13** [comment]
I have more than one Azure SignalR Service each with many hubs. I need to able to connect to a specific service and hub based on the user identity. Then I need to be able to send messages to the appropriate hub. That is  In the negotiate function, depending on the user identity, I need to query a service that returns to me the specific connection of the Azure SignalR  service and hub that this user must connect to. In the SendMessage (messages) I also need to send messages to users in a specific Service and hub based on certain parameters passed in the message.

What I understood  from the docs. and the sample is that the connection to Azure SignalR is put in the function app settings. That is intended to one SignalR service and one Hub, which does not serve my scenario. 

regards

**Comment by JialinXin** [comment]
One function is binding with one service + one hub. 

How you decide the mapping between user and the function? It sounds you may need another function to maintain the routing logic.

**Comment by Raedg13** [comment]
That is true in this case I need to create multiple azure functions per SignalR service and Hub, which I do not want from deployment perspective that will become a nightmare. 

Anyways, I took the code from the azure-functions-signalrservice-extension-master branch and changed the accessor of few classes from internal to public and I was to achieve what I need. Now in my code I can create an instance AzureSignalRClient and pass the connection and the hub name. I hope this will become a feature in the library itself and honestly I do not see any security risk by making AzureSignalRClient a public class.

**Comment by realwanpengli** [comment]
@Raedg13 , have you ever try this [negotiate sample](https://github.com/Azure/azure-functions-signalrservice-extension/blob/dev/samples/simple-chat/csharp/FunctionApp/Functions.cs#L33) and this [broadcast sample](https://github.com/Azure/azure-functions-signalrservice-extension/blob/dev/samples/simple-chat/csharp/FunctionApp/Functions.cs#L52)? e.g. You can obtain hub name in http request or anything else and use `StaticServiceHubContextStore` to create a new hub inside Function. But it only supports C#.

**Comment by Raedg13** [comment]
I have checked the sample you have pointed me to.  I will try it. I think this solves my problem.
Thank  you very much.

**Comment by Raedg13** [comment]
The StaticServiceHubContextStore is found in 1.0.1 -- However, version 1.0.1 is giving me the following  Error : A host error has occurred during startup operation Microsoft.Azure.SignalR.Common: Object reference not set to an instance of an object. Someone else reported this bug and you said you will release it 1.0.2. Do you have a date when it is going to be released?

**Comment by JialinXin** [comment]
1.0.2 is just live, you can update now.
