### ISSUE TITLE
Support sending to users and groups

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-signalrservice-extension#9]
Add support for sending to users and groups.

Current SignalRMessage passed to output binding:

```javascript
{
    "target": "targetMethodName",
    "arguments": [ "arg1", "arg2" ]
}
```

Current API spec: https://github.com/Azure/azure-signalr/blob/dev/docs/swagger.json

#### Option 1

```javascript
{
    "type": "users", // All (default), Users, Groups
    "ids": [ "userId1", "userId2" ], // list of user ids or group names (ignored if sending to all)
    "target": "targetMethodName",
    "arguments": [ "arg1", "arg2" ]
}
```

Type is an enum in .NET, string in other languages.

When sending to specific connection is supported, add a type named "Connections".

#### Option 2

```javascript
{
    "userIds": [ "userId1", "userId2" ],
    "groupNames": [ "groupName1", "groupName2" ],
    "connectionIds": [ "connectionId1", "connectionId2" ], // currently unsupported
    "target": "targetMethodName",
    "arguments": [ "arg1", "arg2" ]
}
```

If no `userIds`, `groupNames`, `connectionIds` supplied, broadcast to all.

What do we do if more than one of `userIds`, `groupNames`, `connectionIds` are supplied? Throw exception? Make multiple API calls to send to all message types?

@chenkennt Thoughts on these options or have any other suggestions?

**Comment by fernandoBRS** [comment]
@anthonychu do you have any release date estimates for this feature?

**Comment by codyclay88** [comment]
@anthonychu  I like option 2 as well. 
I'm also wondering if there is any estimated release date for the "groups" feature. Currently we are developing a prototype for an application that has (somewhat accidentally) become completely serverless through the use of Azure Functions and CosmosDb. We are currently sending real-time updates to user groups through the Pusher Channels API in our Azure Functions, but if Azure SignalR Service could provide that same grouping functionality in a native way through Azure Functions then we would LOVE to keep everything under the Azure umbrella. 

Great work so far though!
